version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - KTOR_APPLICATION_MODULES=com.orderbook.ApplicationKt.module
      - KTOR_DEPLOYMENT_PORT=8080
      - JWT_SECRET=secret
      - JWT_ISSUER=http://localhost:8080
      - JWT_AUDIENCE=http://localhost:8080/orders
      - JWT_REALM=orders