ktor:
    application:
        modules:
            - com.orderbook.ApplicationKt.module
    deployment:
        port: 8080
jwt:
    secret: "secret"
    issuer: "http://localhost:8080"
    audience: "http://localhost:8080/orders"
    realm: "orders"